### ISSUE TITLE
cannot find adt-simple

### ISSUE THREAD

**Issue by arnau** [folktale/core.check#1]
Hi, after a fresh install `core.check` fails to require because it cannot find `adt-simple`.

core.check version: 0.1.0
node version: v0.10.36
platform: Debian 8.0

Steps (clean environment):

```
$ npm install core.check
$ node
> var check = require('core.check')
Error: Cannot find module 'adt-simple'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/deal/node_modules/core.check/lib/index.js:37:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

If I install adt-simple manually it works as expected:

```
$ npm install core.check adt-simple
$ node
> var check = require('core.check');
undefined
> check.assert(check.String(1));
```

**Comment by robotlolita** [comment]
Thanks. `adt-simple` was listed as a devDependency instead of a core dependency. Should be fixed now :)

**Comment by arnau** [comment]
Great, thanks!
